version: "2"
services:
  web:
    image: "128935259397.dkr.ecr.us-east-2.amazonaws.com/testudo-collabo:latest"
    ports:
      - 80:8000
    environment:
      - REDIS_PASS=${REDIS_PASS}
    links:
      - redis
    mem_limit: "750000k"
  redis:
    image: "redis:6-alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    environment:
      - REDIS_REPLICATION_MODE=master
    mem_limit: "250000k"
